server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/static/,file:/F:/upload/
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/personaltravel?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.zgw.personaltravel.entity
#showSql
logging:
  level:
    com:
      zgw:
        personaltravel:
          mapper : debug

